### ISSUE TITLE
如何使得agent能走不同的迷宫？

### ISSUE THREAD

**Issue by ShowiBin** [AryCra07/DQNMazeRobot#1]
尝试了很久如何让agent足够训练好后，在测试阶段能走不同的迷宫.
但始终没成功。

**Comment by AryCra07** [comment]
AutoReply:Hello, this is a mail box of 沈原灏. Now I have received your email successfully:-)

**Comment by AryCra07** [comment]
按说训练好的agent可以走出不同大小的迷宫，不过想较优结果需要权衡参数和网络结构:)

**Comment by ShowiBin** [comment]
嗯嗯 :):)

**Comment by AryCra07** [comment]
AutoReply:Hello, this is a mail box of 沈原灏. Now I have received your email successfully:-)
